jobnow_home:
    path: "/"
    defaults: { _controller: AppBundle:App:index }
jobnow_contact:
    locales:
        en: "/contact"
        fr: "/contacter"
    defaults: { _controller: AppBundle:Contact:contact }
jobnow_credit:
    locales:
        en: "/employer/credit"
        fr: "/employeur/credit"
    defaults: { _controller: AppBundle:Credit:credit }
jobnow_bills:
    locales:
        en: "/employer/bills"
        fr: "/employeur/facture"
    defaults: { _controller: AppBundle:Credit:bills }
jobnow_bills_generate:
    locales:
        en: "/employer/bills/pdf"
        fr: "/employeur/facture/pdf"
    defaults: { _controller: AppBundle:Credit:generateBill }
jobnow_payment:
    locales:
        en: "/employer/payment/{id}"
        fr: "/employeur/paiement/{id}"
    defaults: { _controller: AppBundle:Credit:credit }
contact_us_page:
    locales:
        en: "/contact-us-page"
        fr: "/page-contacter-nous"
    defaults: { _controller: AppBundle:Contact:contactUsPage }
about_us:
    locales:
        en: "/about-us"
        fr: "/a-propos"
    defaults: { _controller: AppBundle:App:aboutPage }
faq_page:
    path: "/faq"
    defaults: { _controller: AppBundle:App:faqPage }
privacy_page:
    locales:
        en: "/privacy"
        fr: "/vie-privee"
    defaults: { _controller: AppBundle:App:privacyPage }
legal_page:
    locales:
        en: "/legal"
        fr: "/legale"
    defaults: { _controller: AppBundle:App:legalPage }
howitwork_page:
    locales:
        en: "/how-it-work"
        fr: "/guide-utilisation"
    defaults: { _controller: AppBundle:App:howitworkPage }
create_notification:
    locales:
        en: "/create-notification"
        fr: "/creation-notification"
    defaults: { _controller: AppBundle:Notification:create }
create_search_notification:
    locales:
        en: "/create-search-notification"
        fr: "/creation-notification-recherche"
    defaults: { _controller: AppBundle:Notification:createSearch }
delete_notification:
    locales:
        en: "/delete-notification/{id}"
        fr: "/supprimer-notification/{id}"
    defaults: { _controller: AppBundle:Notification:delete }
send_notification:
    locales:
        en: "/send-notification"
        fr: "/envoyer-notification"
    defaults: { _controller: AppBundle:Notification:send }
send_search_notification:
    locales:
        en: "/send-search-notification"
        fr: "/envoyer-notification-recherche"
    defaults: { _controller: AppBundle:Notification:sendSearch }
create_favorite:
    locales:
        en: "/create-favorite"
        fr: "/creation-favori"
    defaults: { _controller: AppBundle:Favorite:create }
delete_favorite:
    locales:
        en: "/delete-favorite"
        fr: "/supprimer-favori"
    defaults: { _controller: AppBundle:Favorite:delete }
jobnow_sitemap:
    path: "/sitemap.xml"
    defaults: { _controller: AppBundle:Sitemap:sitemap }
    requirements: {_format: "xml"}
user_already_exist:
    locales:
        en: "/user-already-exist"
        fr: "/utilisateur-existe-deja"
    defaults: { _controller: AppBundle:App:checkUserAlreadyExist }