#    ai_jobnow.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
  app.user_register:
      class: AppBundle\Service\RegisterUser
      arguments: ['@fos_user.user_manager','@security.token_storage','@session']
  app.credit_info:
      class: AppBundle\Service\CreditInfo
  app.client.stripe:
      class: AppBundle\Service\StripeClient
      arguments: ['%stripe_secret_key%', '%payment%', '@doctrine.orm.entity_manager', '@logger']
  app.offer_generate_url:
        class: AppBundle\Service\GenerateUrl
        arguments: ['@translator']
  app.redirect.after.login:
        class: AppBundle\Service\AfterLoginRedirect
        arguments: ['@router']






