create_employer:
    locales:
        en: "/register"
        fr: "/inscription"
    defaults: { _controller: EmployerBundle:Employer:create }
edit_employer:
    locales:
        en: "/edit"
        fr: "/editer"
    defaults: { _controller: EmployerBundle:Employer:edit }
delete_employer:
    locales:
        en: "/delete/{id}"
        fr: "/supprimer/{id}"
    defaults: { _controller: EmployerBundle:Employer:delete }

show_employer:
    locales:
        en: "/{id}"
        fr: "/{id}"
    defaults: { _controller: EmployerBundle:Employer:show }
    requirements:
        id: \d+
list_employer:
    locales:
        en: "/list-employer"
        fr: "/liste-employeur"
    defaults: { _controller: EmployerBundle:Employer:list }
dashboard_employer:
    locales:
        en: "/dashboard/{archived}"
        fr: "/tableaux-de-bord/{archived}"
    defaults: { _controller: EmployerBundle:Employer:dashboard , archived: 0}
    requirements:
      archived: 0|1
post_offer:
    locales:
        en: "/post-offer"
        fr: "/creation-offre"
    defaults: { _controller: EmployerBundle:Offer:post }
edit_offer:
    locales:
        en: "/edit-offer/{id}"
        fr: "/edition-offre/{id}"
    defaults: { _controller: EmployerBundle:Offer:edit }
    requirements:
      id: \d+
delete_offer:
    locales:
        en: "/delete-offer/{id}"
        fr: "/supprimer-offre/{id}"
    defaults: { _controller: EmployerBundle:Offer:delete }
    requirements:
      id: \d+
activate_offer:
    locales:
        en: "/activate-offer/{id}"
        fr: "/activer-offre/{id}"
    defaults: { _controller: EmployerBundle:Offer:activate }
    requirements:
      id: \d+
show_offer:
    locales:
        en: "/offer/{url}/{id}"
        fr: "/offre/{url}/{id}"
    defaults: { _controller: EmployerBundle:Offer:show }
    requirements:
        url:    .*
apply_offer:
    locales:
        en: "/apply-offer/{id}"
        fr: "/postuler-offre/{id}"
    defaults: { _controller: EmployerBundle:Offer:apply }
    requirements:
      id: \d+
search_offer:
    locales:
        en: "/search-offer"
        fr: "/chercher-offre"
    defaults: { _controller: EmployerBundle:Offer:search }
search_page_offer:
    locales:
        en: "/search-offer-page"
        fr: "/page-chercher-offre"
    defaults: { _controller: EmployerBundle:Offer:searchPage }
boost_offers:
    locales:
        en: "/boost-offer"
        fr: "/booster-offre"
    defaults: { _controller: EmployerBundle:Offer:boost }
featured_employer_page:
    locales:
        en: "/featured-employer"
        fr: "/employeur-en-avant"
    defaults: { _controller: EmployerBundle:Employer:featuredEmployerPage }
reserve_featured_employer:
    locales:
        en: "/reserve-featured-employer"
        fr: "/reserver-employeur-en-avant"
    defaults: { _controller: EmployerBundle:Employer:reserveFeaturedEmployer }
delete_featured_employer:
    locales:
        en: "/delete-featured-employer"
        fr: "/supprimer-employeur-en-avant"
    defaults: { _controller: EmployerBundle:Employer:deleteFeaturedEmployer }
featured_offer_page:
    locales:
        en: "/featured-offer"
        fr: "/offre-en-avant"
    defaults: { _controller: EmployerBundle:Employer:featuredOfferPage }
reserve_featured_offer:
    locales:
        en: "/reserve-featured-offer"
        fr: "/reserver-offre-en-avant"
    defaults: { _controller: EmployerBundle:Employer:reserveFeaturedOffer }
delete_featured_offer:
    locales:
        en: "/delete-featured-offer"
        fr: "/supprimer-offre-en-avant"
    defaults: { _controller: EmployerBundle:Employer:deleteFeaturedOffer }
buy_slot:
    locales:
        en: "/buy-slot"
        fr: "/acheter-slot"
    defaults: { _controller: EmployerBundle:Employer:buySlot }
add_to_slot:
    locales:
        en: "/add-to-slot/{id}"
        fr: "/ajouter-aux-slot/{id}"
    defaults: { _controller: EmployerBundle:Employer:addToSlot }
    requirements:
      id: \d+
remove_from_slot:
    locales:
        en: "/remove-from-slot/{id}"
        fr: "/enlever-du-slot/{id}"
    defaults: { _controller: EmployerBundle:Employer:removeFromSlot }
    requirements:
      id: \d+
empty_slot:
    locales:
        en: "/empty-slot/{id}"
        fr: "/vider-slot/{id}"
    defaults: { _controller: EmployerBundle:Employer:EmptySlot }
    requirements:
      id: \d+